sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --frozen-lockfile
  - yarn global add coveralls
script:
  - yarn run test
after_success:
  - cat ./coverage/lcov.info | coveralls
branches:
  only:
    - master
